### PR TITLE
implemented multiple color in one row like morefontcolors plugin

### PR DESCRIPTION
**Pull request by abuzakaria**
Added options to add multiple colors in single row similar to the plugin [moodle-atto_morefontcolors](https://github.com/TUM-MZ/moodle-atto_morefontcolors). In settings, color needs to be added like the following example:

> # FFFFFF #EF4540
> # FFCF35 #7D9FD3
> # 98CA3E #333333

It will appear in the editor like this:

image

### CODE REVIEW

**Comment by micaherne** [comment]
Hi, I tested this change out, and it's good, but there's a small problem. When you mouse over the colour you want to choose, the whole row is highlighted rather than just that item. If you were able to fix that I'd be happy to pull it into the main codebase.

**Comment by abuzakaria** [comment]
Fixed: fa2a3441d1af36f417555c612a320e0199b655a5

**Comment by abias** [comment]
Hi, 
do you think you can merge and publish this patch sometime soon? Your "brother plugin" https://github.com/ndunand/moodle-atto_morefontcolors has already merged this patch several weeks ago...

Thanks,
Alex

**Comment by abias** [comment]
_bump_

**Comment by ndunand** [comment]
A new version of this plugin has now been released, which addresses this.

**Pull request closed without merging**
